name: Code coverage

  #on:
  #push:
  #  branches:
  #  - master
  #pull_request:

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.7'

    steps:
      - uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@master
        with:
           python-version: 3.7

      - name: Generate coverage report
        run: |
          make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
