name: Build and publish docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pip install sphinx
          make -C docs html

#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          repository-name: prophyle/prophyle.github.io
#          branch: master # The branch the action should deploy to.
#          toke:
#          folder: docs/.build/html # The folder the action should deploy.


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   # Recommended for this usage
          external_repository: prophyle/prophyle.github.io
          publish_branch: master
          publish_dir: ./docs/.build/html

